version: "3.8"

services:
  redis:
      image: "redis:alpine"
      ports:
        - "6379:6379"
      networks:
        - chatnet
      command: ["redis-server", "--bind", "0.0.0.0"]  
  chatapp:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis:6379
    networks:
      - chatnet

  

networks:
  chatnet:
    driver: bridge
